<?php
add_action( 'init', 'rf_register_post_type' );
function rf_register_post_type() {
    $labels = [
        'name'                     => esc_html__( 'Members' ),
        'singular_name'            => esc_html__( 'Member' ),
        'add_new'                  => esc_html__( 'Add New' ),
        'add_new_item'             => esc_html__( 'Add new member' ),
        'edit_item'                => esc_html__( 'Edit Member' ),
        'new_item'                 => esc_html__( 'New Member' ),
        'view_item'                => esc_html__( 'View Member' ),
        'view_items'               => esc_html__( 'View Members' ),
        'search_items'             => esc_html__( 'Search Members' ),
        'not_found'                => esc_html__( 'No members found' ),
        'not_found_in_trash'       => esc_html__( 'No members found in Trash' ),
        'parent_item_colon'        => esc_html__( 'Parent Member:' ),
        'all_items'                => esc_html__( 'All Members' ),
        'archives'                 => esc_html__( 'Member Archives' ),
        'attributes'               => esc_html__( 'Member Attributes' ),
        'insert_into_item'         => esc_html__( 'Insert into member' ),
        'uploaded_to_this_item'    => esc_html__( 'Uploaded to this member' ),
        'featured_image'           => esc_html__( 'Featured image' ),
        'set_featured_image'       => esc_html__( 'Set featured image' ),
        'remove_featured_image'    => esc_html__( 'Remove featured image' ),
        'use_featured_image'       => esc_html__( 'Use as featured image' ),
        'menu_name'                => esc_html__( 'Members' ),
        'filter_items_list'        => esc_html__( 'Filter members list' ),
        'items_list_navigation'    => esc_html__( 'Members list navigation' ),
        'items_list'               => esc_html__( 'Members list' ),
        'item_published'           => esc_html__( 'Member published' ),
        'item_published_privately' => esc_html__( 'Member published privately' ),
        'item_reverted_to_draft'   => esc_html__( 'Member reverted to draft' ),
        'item_scheduled'           => esc_html__( 'Member scheduled' ),
        'item_updated'             => esc_html__( 'Member updated' ),
        'text_domain'              => esc_html__( 'rf' ),
    ];
    $args = [
        'label'               => esc_html__( 'Members' ),
        'labels'              => $labels,
        'description'         => '',
        'public'              => true,
        'hierarchical'        => false,
        'exclude_from_search' => true,
        'publicly_queryable'  => true,
        'show_ui'             => true,
        'show_in_nav_menus'   => true,
        'show_in_admin_bar'   => true,
        'show_in_rest'        => true,
        'menu_position'       => null,
        'query_var'           => true,
        'can_export'          => true,
        'delete_with_user'    => true,
        'has_archive'         => false,
        'rest_base'           => '',
        'show_in_menu'        => true,
        'menu_icon'           => 'dashicons-images-alt2',
        'capability_type'     => 'page',
        'supports'            => ['title', 'editor', 'thumbnail'],
        'taxonomies'          => [],
        'rewrite'             => [
            'with_front' => false,
            'slug' => 'leader'
        ],
    ];

    register_post_type( 'member', $args );

    $sticker_labels = [
        'name'                     => esc_html__( 'Stickers'),
        'singular_name'            => esc_html__( 'Sticker'),
        'add_new'                  => esc_html__( 'Add New'),
        'add_new_item'             => esc_html__( 'Add new sticker'),
        'edit_item'                => esc_html__( 'Edit sticker'),
        'new_item'                 => esc_html__( 'New sticker'),
        'view_item'                => esc_html__( 'View sticker'),
        'view_items'               => esc_html__( 'View Stickers'),
        'search_items'             => esc_html__( 'Search Stickers'),
        'not_found'                => esc_html__( 'No stickers found'),
        'not_found_in_trash'       => esc_html__( 'No stickers found in Trash'),
        'parent_item_colon'        => esc_html__( 'Parent sticker:'),
        'all_items'                => esc_html__( 'All Stickers'),
        'archives'                 => esc_html__( 'Sticker Archives'),
        'attributes'               => esc_html__( 'Sticker Attributes'),
        'insert_into_item'         => esc_html__( 'Insert into sticker'),
        'uploaded_to_this_item'    => esc_html__( 'Uploaded to this sticker'),
        'featured_image'           => esc_html__( 'Featured image'),
        'set_featured_image'       => esc_html__( 'Set featured image'),
        'remove_featured_image'    => esc_html__( 'Remove featured image'),
        'use_featured_image'       => esc_html__( 'Use as featured image'),
        'menu_name'                => esc_html__( 'Stickers'),
        'filter_items_list'        => esc_html__( 'Filter stickers list'),
        'items_list_navigation'    => esc_html__( 'Stickers list navigation'),
        'items_list'               => esc_html__( 'Stickers list'),
        'item_published'           => esc_html__( 'Sticker published'),
        'item_published_privately' => esc_html__( 'Sticker published privately'),
        'item_reverted_to_draft'   => esc_html__( 'Sticker reverted to draft'),
        'item_scheduled'           => esc_html__( 'Sticker scheduled'),
        'item_updated'             => esc_html__( 'Sticker updated'),
        'text_domain'              => esc_html__( 'rf'),
    ];
    $sticker_args = [
        'label'               => esc_html__( 'Stickers'),
        'labels'              => $sticker_labels,
        'description'         => '',
        'public'              => true,
        'hierarchical'        => false,
        'exclude_from_search' => true,
        'publicly_queryable'  => true,
        'show_ui'             => true,
        'show_in_nav_menus'   => true,
        'show_in_admin_bar'   => true,
        'show_in_rest'        => true,
        'menu_position'       => 20,
        'query_var'           => true,
        'can_export'          => true,
        'delete_with_user'    => true,
        'has_archive'         => false,
        'rest_base'           => '',
        'show_in_menu'        => true,
        'menu_icon'           => 'dashicons-smiley',
        'capability_type'     => 'page',
        'supports'            => ['title'],
        'taxonomies'          => [],
        'rewrite'             => [
            'with_front' => false,
        ],
    ];

    register_post_type( 'sticker', $sticker_args );

    $cal_labels = [
        'name'                     => esc_html__( 'Calendars'),
        'singular_name'            => esc_html__( 'Calendar'),
        'add_new'                  => esc_html__( 'Add New'),
        'add_new_item'             => esc_html__( 'Add new calendar'),
        'edit_item'                => esc_html__( 'Edit Calendar'),
        'new_item'                 => esc_html__( 'New Calendar'),
        'view_item'                => esc_html__( 'View Calendar'),
        'view_items'               => esc_html__( 'View Calendars'),
        'search_items'             => esc_html__( 'Search Calendars'),
        'not_found'                => esc_html__( 'No calendars found'),
        'not_found_in_trash'       => esc_html__( 'No calendars found in Trash'),
        'parent_item_colon'        => esc_html__( 'Parent Calendar:'),
        'all_items'                => esc_html__( 'All Calendars'),
        'archives'                 => esc_html__( 'Calendar Archives'),
        'attributes'               => esc_html__( 'Calendar Attributes'),
        'insert_into_item'         => esc_html__( 'Insert into calendar'),
        'uploaded_to_this_item'    => esc_html__( 'Uploaded to this calendar'),
        'featured_image'           => esc_html__( 'Featured image'),
        'set_featured_image'       => esc_html__( 'Set featured image'),
        'remove_featured_image'    => esc_html__( 'Remove featured image'),
        'use_featured_image'       => esc_html__( 'Use as featured image'),
        'menu_name'                => esc_html__( 'Calendars'),
        'filter_items_list'        => esc_html__( 'Filter calendars list'),
        'items_list_navigation'    => esc_html__( 'Calendars list navigation'),
        'items_list'               => esc_html__( 'Calendars list'),
        'item_published'           => esc_html__( 'Calendar published'),
        'item_published_privately' => esc_html__( 'Calendar published privately'),
        'item_reverted_to_draft'   => esc_html__( 'Calendar reverted to draft'),
        'item_scheduled'           => esc_html__( 'Calendar scheduled'),
        'item_updated'             => esc_html__( 'Calendar updated'),
    ];
    $cal_args = [
        'label'               => esc_html__( 'Calendars'),
        'labels'              => $cal_labels,
        'description'         => '',
        'public'              => true,
        'hierarchical'        => false,
        'exclude_from_search' => true,
        'publicly_queryable'  => true,
        'show_ui'             => true,
        'show_in_nav_menus'   => true,
        'show_in_admin_bar'   => true,
        'show_in_rest'        => true,
        'menu_position'       => 20,
        'query_var'           => true,
        'can_export'          => true,
        'delete_with_user'    => true,
        'has_archive'         => false,
        'rest_base'           => '',
        'show_in_menu'        => true,
        'menu_icon'           => 'dashicons-format-gallery',
        'capability_type'     => 'page',
        'supports'            => ['title'],
        'taxonomies'          => [],
        'rewrite'             => [
            'with_front' => false,
        ],
    ];

    register_post_type( 'calendar', $cal_args );
}
