<?php
// Register Custom Post Type
function speaker_post_type() {

	$labels = array(
		'name'                  => _x( 'Speaker', 'Post Type General Name', 'obe' ),
		'singular_name'         => _x( 'Speaker', 'Post Type Singular Name', 'obe' ),
		'menu_name'             => __( 'Speakers', 'obe' ),
		'name_admin_bar'        => __( 'Speakers', 'obe' ),
		'archives'              => __( 'Item Archives', 'obe' ),
		'attributes'            => __( 'Item Attributes', 'obe' ),
		'parent_item_colon'     => __( 'Parent Item:', 'obe' ),
		'all_items'             => __( 'All Items', 'obe' ),
		'add_new_item'          => __( 'Add New Item', 'obe' ),
		'add_new'               => __( 'Add New', 'obe' ),
		'new_item'              => __( 'New Item', 'obe' ),
		'edit_item'             => __( 'Edit Item', 'obe' ),
		'update_item'           => __( 'Update Item', 'obe' ),
		'view_item'             => __( 'View Item', 'obe' ),
		'view_items'            => __( 'View Items', 'obe' ),
		'search_items'          => __( 'Search Item', 'obe' ),
		'not_found'             => __( 'Not found', 'obe' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'obe' ),
		'featured_image'        => __( 'Featured Image', 'obe' ),
		'set_featured_image'    => __( 'Set featured image', 'obe' ),
		'remove_featured_image' => __( 'Remove featured image', 'obe' ),
		'use_featured_image'    => __( 'Use as featured image', 'obe' ),
		'insert_into_item'      => __( 'Insert into item', 'obe' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'obe' ),
		'items_list'            => __( 'Items list', 'obe' ),
		'items_list_navigation' => __( 'Items list navigation', 'obe' ),
		'filter_items_list'     => __( 'Filter items list', 'obe' ),
	);
	$args = array(
		'label'                 => __( 'Speaker', 'obe' ),
		'description'           => __( 'Speaker', 'obe' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'thumbnail' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'menu_icon'          	=> 'dashicons-admin-users',
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
	);
	register_post_type( 'speaker', $args );

}
add_action( 'init', 'speaker_post_type', 0 );

/**
 * Generated by the WordPress Meta Box Generator
 * https://jeremyhixon.com/tool/wordpress-meta-box-generator/
 * 
 * Retrieving the values:
 * Company = get_post_meta( get_the_ID(), 'advanced_options_speaker_company', true )
 * Position = get_post_meta( get_the_ID(), 'advanced_options_speaker_position', true )
 *  Description = get_post_meta( get_the_ID(), 'advanced_options_speaker_description', true )
 * Linkedin = get_post_meta( get_the_ID(), 'advanced_options_speaker_linkedin', true )
 * Logo = get_post_meta( get_the_ID(), 'advanced_options_speaker_logo', true )
 */
class advanced_options_speaker {
	private $config = '{"title":"Speaker","description":"Speaker","prefix":"advanced_options_speaker_","domain":"OBE","class_name":"advanced_options_speaker","context":"normal","priority":"default","cpt":"speaker","fields":[
		{"type":"text","label":"Company","id":"advanced_options_speaker_company"},
		{"type":"text","label":"Position","id":"advanced_options_speaker_position"},
		{"type":"text","label":" Description","id":"advanced_options_speaker_description"},
		{"type":"url","label":"Linkedin","id":"advanced_options_speaker_linkedin"},
		{"type":"media","label":"Logo","return":"url","modal-title":"Choose a file","modal-button":"Select this file","id":"advanced_options_speaker_logo"}]}';

	public function __construct() {
		$this->config = json_decode( $this->config, true );
		$this->process_cpts();
		add_action( 'add_meta_boxes', [ $this, 'add_meta_boxes' ] );
		add_action( 'admin_enqueue_scripts', [ $this, 'admin_enqueue_scripts' ] );
		add_action( 'admin_head', [ $this, 'admin_head' ] );
		add_action( 'save_post', [ $this, 'save_post' ] );
	}

	public function process_cpts() {
		if ( !empty( $this->config['cpt'] ) ) {
			if ( empty( $this->config['post-type'] ) ) {
				$this->config['post-type'] = [];
			}
			$parts = explode( ',', $this->config['cpt'] );
			$parts = array_map( 'trim', $parts );
			$this->config['post-type'] = array_merge( $this->config['post-type'], $parts );
		}
	}

	public function add_meta_boxes() {
		foreach ( $this->config['post-type'] as $screen ) {
			add_meta_box(
				sanitize_title( $this->config['title'] ),
				$this->config['title'],
				[ $this, 'add_meta_box_callback' ],
				$screen,
				$this->config['context'],
				$this->config['priority']
			);
		}
	}

	public function admin_enqueue_scripts() {
		global $typenow;
		if ( in_array( $typenow, $this->config['post-type'] ) ) {
			wp_enqueue_media();
		}
	}

	public function admin_head() {
		global $typenow;
		if ( in_array( $typenow, $this->config['post-type'] ) ) {
			?><script>
				jQuery.noConflict();
				(function($) {
					$(function() {
						$('body').on('click', '.rwp-media-toggle', function(e) {
							e.preventDefault();
							let button = $(this);
							let rwpMediaUploader = null;
							rwpMediaUploader = wp.media({
								title: button.data('modal-title'),
								button: {
									text: button.data('modal-button')
								},
								multiple: true
							}).on('select', function() {
								let attachment = rwpMediaUploader.state().get('selection').first().toJSON();
								button.prev().val(attachment[button.data('return')]);
							}).open();
						});
					});
				})(jQuery);
			</script><?php
			?><?php
		}
	}

	public function save_post( $post_id ) {
		foreach ( $this->config['fields'] as $field ) {
			switch ( $field['type'] ) {
				case 'url':
					if ( isset( $_POST[ $field['id'] ] ) ) {
						$sanitized = esc_url_raw( $_POST[ $field['id'] ] );
						update_post_meta( $post_id, $field['id'], $sanitized );
					}
					break;
				default:
					if ( isset( $_POST[ $field['id'] ] ) ) {
						$sanitized = sanitize_text_field( $_POST[ $field['id'] ] );
						update_post_meta( $post_id, $field['id'], $sanitized );
					}
			}
		}
	}

	public function add_meta_box_callback() {
		echo '<div class="rwp-description">' . $this->config['description'] . '</div>';
		$this->fields_table();
	}

	private function fields_table() {
		?><table class="form-table" role="presentation">
			<tbody><?php
				foreach ( $this->config['fields'] as $field ) {
					?><tr>
						<th scope="row"><?php $this->label( $field ); ?></th>
						<td><?php $this->field( $field ); ?></td>
					</tr><?php
				}
			?></tbody>
		</table><?php
	}

	private function label( $field ) {
		switch ( $field['type'] ) {
			case 'media':
				printf(
					'<label class="" for="%s_button">%s</label>',
					$field['id'], $field['label']
				);
				break;
			default:
				printf(
					'<label class="" for="%s">%s</label>',
					$field['id'], $field['label']
				);
		}
	}

	private function field( $field ) {
		switch ( $field['type'] ) {
			case 'media':
				$this->input( $field );
				$this->media_button( $field );
				break;
			default:
				$this->input( $field );
		}
	}

	private function input( $field ) {
		if ( $field['type'] === 'media' ) {
			$field['type'] = 'text';
		}
		printf(
			'<input class="regular-text %s" id="%s" name="%s" %s type="%s" value="%s">',
			isset( $field['class'] ) ? $field['class'] : '',
			$field['id'], $field['id'],
			isset( $field['pattern'] ) ? "pattern='{$field['pattern']}'" : '',
			$field['type'],
			$this->value( $field )
		);
	}

	private function media_button( $field ) {
		printf(
			' <button class="button rwp-media-toggle" data-modal-button="%s" data-modal-title="%s" data-return="%s" id="%s_button" name="%s_button" type="button">%s</button>',
			isset( $field['modal-button'] ) ? $field['modal-button'] : __( 'Select this file', 'OBE' ),
			isset( $field['modal-title'] ) ? $field['modal-title'] : __( 'Choose a file', 'OBE' ),
			$field['return'],
			$field['id'], $field['id'],
			isset( $field['button-text'] ) ? $field['button-text'] : __( 'Upload', 'OBE' )
		);
	}

	private function value( $field ) {
		global $post;
		if ( metadata_exists( 'post', $post->ID, $field['id'] ) ) {
			$value = get_post_meta( $post->ID, $field['id'], true );
		} else if ( isset( $field['default'] ) ) {
			$value = $field['default'];
		} else {
			return '';
		}
		return str_replace( '\u0027', "'", $value );
	}

}
new advanced_options_speaker;